// <auto-generated />
namespace NewDayNewLeaf.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class BlathersSaying : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BlathersSaying));
        
        string IMigrationMetadata.Id
        {
            get { return "201306031752092_BlathersSaying"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
